Initial Build v0.3.9
AnacondaRecipes/ipython-sql-feedstock pull request #1
Opened 2022-12-20 18:29 UTC by ViridianMelody

Jira issue: https://anaconda.atlassian.net/browse/PKG-750
Upstream Repo: https://github.com/catherinedevlin/ipython-sql

2022-12-20 18:30 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_c2uonffh5o/clone/recipe/meta.yaml:1: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_c2uonffh5o/clone/recipe/meta.yaml:17: avoid_noarch: noarch: python packages should be avoided
ERROR: /tmp/abs_c2uonffh5o/clone/recipe/meta.yaml:22: missing_wheel: For pypi packages, wheel should be present in the host section
ERROR: /tmp/abs_c2uonffh5o/clone/recipe/meta.yaml:37: invalid_url: https://pypi.python.org/pypi/ipython-sql : URL domain redirect pypi.python.org ->  pypi.org
WARNING: /tmp/abs_c2uonffh5o/clone/recipe/meta.yaml:45: missing_license_url: The recipe is missing a license_url
ERROR: /tmp/abs_c2uonffh5o/clone/recipe/meta.yaml:45: missing_license_family: The recipe is missing the `about/license_family` key.
ERROR: /tmp/abs_c2uonffh5o/clone/recipe/meta.yaml:45: missing_doc_url: The recipe is missing a doc_url
WARNING: /tmp/abs_c2uonffh5o/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
Errors were found

</details>

2022-12-21 22:42 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_9b117g3r_t/clone/recipe/meta.yaml:1: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: /tmp/abs_9b117g3r_t/clone/recipe/meta.yaml:17: avoid_noarch: noarch: python packages should be avoided
ERROR: /tmp/abs_9b117g3r_t/clone/recipe/meta.yaml:22: missing_wheel: For pypi packages, wheel should be present in the host section
ERROR: /tmp/abs_9b117g3r_t/clone/recipe/meta.yaml:37: invalid_url: https://pypi.python.org/pypi/ipython-sql : URL domain redirect pypi.python.org ->  pypi.org
WARNING: /tmp/abs_9b117g3r_t/clone/recipe/meta.yaml:45: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_9b117g3r_t/clone/recipe/meta.yaml:45: missing_doc_source_url: The recipe is missing a doc_source_url
ERROR: /tmp/abs_9b117g3r_t/clone/recipe/meta.yaml:45: missing_license_family: The recipe is missing the `about/license_family` key.
ERROR: /tmp/abs_9b117g3r_t/clone/recipe/meta.yaml:45: missing_doc_url: The recipe is missing a doc_url
Errors were found

</details>

2022-12-21 22:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_54ii7fyn3o/clone/recipe/meta.yaml:51: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_54ii7fyn3o/clone/recipe/meta.yaml:51: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-22 18:13 UTC, ryanskeith requested changes
We shouldn't add the patch for Python 2.

2022-12-22 18:13 UTC, ryanskeith commented on recipe/github__sodre__ipython-sql__py27-setup.patch
> -
I don't think this is required.  We should not be supporting Python 2.

2022-12-22 18:13 UTC, ryanskeith commented on recipe/meta.yaml
> +  home: https://pypi.org/project/ipython-sql/
Pypi, should not be where we are pointing as home.  Pypi points back to the dev url which is better.

2022-12-22 18:13 UTC, ryanskeith commented on recipe/meta.yaml
> +  home: https://pypi.org/project/ipython-sql/
```suggestion
  home: https://github.com/catherinedevlin/ipython-sql
```

2022-12-22 18:16 UTC, ViridianMelody commented on recipe/github__sodre__ipython-sql__py27-setup.patch
> -
This change is to remove the existing patch.

2022-12-22 18:17 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_4fm5fu3geb/clone/recipe/meta.yaml:51: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_4fm5fu3geb/clone/recipe/meta.yaml:51: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-22 18:56 UTC, ryanskeith commented on recipe/github__sodre__ipython-sql__py27-setup.patch
> -
Apologies, it seemed like it was adding it in.

2022-12-22 18:57 UTC, ryanskeith approved these changes
LGTM

2022-12-22 23:40 UTC, ELundby45 approved these changes
LGTM

2022-12-23 08:39 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - wheel
Missing `setuptools`

2022-12-29 19:23 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_8bkj5yqkei/clone/recipe/meta.yaml:52: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_8bkj5yqkei/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-12-29 19:38 UTC, merged

2022-12-29 19:39 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_820f2xcsyf/clone/recipe/meta.yaml:52: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_820f2xcsyf/clone/recipe/meta.yaml:52: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>